#include <LCD_I2C.h>

LCD_I2C lcd(0x27);

void verse_1(){
    delay(9000);
    lcd.setCursor(0, 0);
    lcd.print("Di ko");
    lcd.setCursor(0, 1);
    lcd.print("maintindihan");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ang nilalaman");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ng PUSO");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Tuwing maghawak");
    lcd.setCursor(0, 1);
    lcd.print("ang ating kamay");
    delay(8000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Pinapanalangin");
    lcd.setCursor(0, 1);
    lcd.print("lagi tayong");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("MAGKASAMA");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Hinihiling");
    lcd.setCursor(0, 1);
    lcd.print("Bawat Oras");
     delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Kapiling Ka");
    delay(4000);
    lcd.clear();
    delay(50);
}
void chorus2(){
    lcd.setCursor(0, 0);
    lcd.print("SAAAAA");
    lcd.setCursor(0, 1);
    lcd.print("LAHAAAATTTTTT!");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("ng aking");
    lcd.setCursor(0, 1);
    lcd.print("Ginagawaaaa");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw Lamang");
    delay(4000);
    lcd.setCursor(0, 1);
    lcd.print("Ang nasa isip ko");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("SINTAAAAAAAAA");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Sana'y dina tayo");
    delay(4000);
    delay(50);
    lcd.setCursor(0, 1);
    lcd.print("Magkahiwalay");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Kahit kailan");
    lcd.setCursor(0, 1);
    lcd.print("Pa man");
    delay(8000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw lamang ang");
    lcd.setCursor(0, 1);
    lcd.print("aking");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Minamahal");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw lamang ang");
    lcd.setCursor(0, 1);
    lcd.print("tangi kong");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Inaasam");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Makapiling ka");
    lcd.setCursor(0, 1);
    lcd.print("Habang Buhay");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw Lamang");
    delay(2000);
    lcd.setCursor(0, 1);
    lcd.print("Sinta");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wala na 'kong");
    delay(2000);
    lcd.setCursor(0, 1);
    lcd.print("Hihingin pa");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wala na");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Oooooohhhhhh!");
    delay(5000);
    lcd.clear();
    delay(50);
}

void chorus(){
    lcd.setCursor(0, 0);
    lcd.print("SAAAAA");
    lcd.setCursor(0, 1);
    lcd.print("LAHAAAATTTTTT!");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("ng aking");
    lcd.setCursor(0, 1);
    lcd.print("Ginagawaaaa");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw Lamang");
    delay(4000);
    lcd.setCursor(0, 1);
    lcd.print("Ang nasa isip ko");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("SINTAAAAAAAAA");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Sana'y dina tayo");
    delay(4000);
    delay(50);
    lcd.setCursor(0, 1);
    lcd.print("Magkahiwalay");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Kahit kailan");
    lcd.setCursor(0, 1);
    lcd.print("Pa man");
    delay(8000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw lamang ang");
    lcd.setCursor(0, 1);
    lcd.print("aking");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Minamahal");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw lamang ang");
    lcd.setCursor(0, 1);
    lcd.print("tangi kong");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Inaasam");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Makapiling ka");
    lcd.setCursor(0, 1);
    lcd.print("Habang Buhay");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw Lamang");
    delay(2000);
    lcd.setCursor(0, 1);
    lcd.print("Sinta");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wala na 'kong");
    delay(2000);
    lcd.setCursor(0, 1);
    lcd.print("Hihingin pa");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wala na");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Oooooohhhhhh!");
    delay(5000);
    lcd.clear();
    delay(50);
}

void verse_2(){
    lcd.setCursor(0, 0);  
    lcd.print("Ayoko ng");
    lcd.setCursor(0, 1);
    lcd.print("Maulit pa");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ang nakaraang");
    lcd.setCursor(0, 1);
    lcd.print("ayokong maalala");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Bawat Oras na ");
    lcd.setCursor(0, 1);
    lcd.print("wala ka");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("parang mabigat");
    lcd.setCursor(0, 1);
    lcd.print("na PARUSA");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wag mong");
    lcd.setCursor(0, 1);
    lcd.print("kakalimutan");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Na Kahit Nag iba");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Di ako tumigil");
    delay(3000);
    lcd.setCursor(0, 1);
    lcd.print("Mag mahal sayo");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Sintaaaa");
    delay(2000);
    lcd.clear();
}

void bridge(){
    lcd.setCursor(0, 0);
    lcd.print("Ikaw lamang ang");
    lcd.setCursor(0, 1);
    lcd.print("aking");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Minamahal");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw lamang ang");
    lcd.setCursor(0, 1);
    lcd.print("tangi kong");
    delay(5000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Inaasam");
    delay(3000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Makapiling ka");
    lcd.setCursor(0, 1);
    lcd.print("Habang Buhay");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Ikaw Lamang");
    delay(2000);
    lcd.setCursor(0, 1);
    lcd.print("Sinta");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wala na 'kong");
    delay(2000);
    lcd.setCursor(0, 1);
    lcd.print("Hihingin pa");
    delay(2000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Wala na");
    delay(4000);
    lcd.clear();
    delay(50);
    lcd.setCursor(0, 0);
    lcd.print("Oooooohhhhhh!");
    delay(5000);
    lcd.clear();
    delay(50);
}

void setup() {
  // put your setup code here, to run once:
  lcd.begin();
  lcd.backlight();
}

void loop() {
    verse_1();
    chorus();
    delay(16000);
    verse_2();
    chorus2();
    delay(32000);
    bridge();
    delay(5000);
  }
